---
abstract: 'add a file listing all contributors'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0.88
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-ContributorsFile
provides:
  Dist::Zilla::Plugin::ContributorsFile:
    file: lib/Dist/Zilla/Plugin/ContributorsFile.pm
    version: v0.1.0
requires:
  Dist::Zilla::File::InMemory: 0
  Dist::Zilla::Role::FileGatherer: 0
  Dist::Zilla::Role::Plugin: 0
  Dist::Zilla::Role::TextTemplate: 0
  Moose: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-ContributorsFile
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-ContributorsFile/
  repository: https://github.com/yanick/Dist-Zilla-Plugin-ContributorsFile.git
version: 0.1.0
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
